stop_slot:
  name: Stop slot
  description: Stop charging/discharging on a single MC3000 slot.
  fields:
    slot:
      name: Slot
      description: Slot number, 1 to 4.
      required: true
      selector:
        number:
          min: 1
          max: 4
          mode: box

stop_all:
  name: Stop all slots
  description: Stop charging/discharging on all MC3000 slots.

start_slot:
  name: Start slot
  description: Start the currently configured MC3000 program on a single slot.
  fields:
    slot:
      name: Slot
      description: Slot number, 1 to 4.
      required: true
      selector:
        number:
          min: 1
          max: 4
          mode: box

refresh:
  name: Refresh data
  description: Force an immediate data refresh from the MC3000.
